### ISSUE TITLE
windows下跑不起来

### ISSUE THREAD

**Issue by daniel-007** [macross-contrib/vuejsto#1]
# vuejsto/vendor/github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
然后去看了：https://github.com/mattn/go-sqlite3/issues/212，好晕，然后我改成MySQL了。。。
求指导。。

**Comment by insionng** [comment]
@daniel-007 你看到你的出错提示了吗？提示没有gcc编译器，因为sqlite3依赖cgo，所以需要gcc，你可以安装tdm-gcc：http://tdm-gcc.tdragon.net/download

**Comment by insionng** [comment]
@daniel-007 改成mysql也是可以的，把models里的sqlite驱动去掉，换成mysql的即可~

**Comment by insionng** [comment]
@daniel-007 还有问题吗？如果没有问题了，issue将会关闭~

**Comment by daniel-007** [comment]
GetTasks()报错：panic: runtime error: invalid memory address or nil pointer dereference

**Comment by daniel-007** [comment]
你干脆来个mysql版本的例子吧，我是windows环境。

**Comment by daniel-007** [comment]
修改成mysql数据库，GetTasks()里DB对象是空的。

**Comment by insionng** [comment]
@daniel-007 我写个通用的吧 等下传上来~

**Comment by daniel-007** [comment]
@insionng 好的。最好能整合个ORM框架，就是个基本的web单体应用的例子了，方便大家理解学习。

**Comment by insionng** [comment]
@daniel-007 已经用XORM重写了一个版本了，请更新最新版本~

**Comment by daniel-007** [comment]
@insionng 效率真高，赞！
